site_name: Hacktoberfest Korea
copyright: This is korean fan page of Hacktoberfest
site_url: 'https://www.hacktoberfestkorea.com/'

theme:
  name: material
  language: kr
  custom_dir: 'theme'
  palette:
    scheme: default
    primary: deep purple
  favicon: assets/favicon.png

nav:
  - Home: index.md
  - 초보자용 가이드: beginners_guide.md
  - 작업환경 구성 방법: build.md
  - 자주 묻는 질문: faq.md

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
