site_name: Hacktoberfest Korea 2023
copyright: Hacktoberfest Kora 2023
site_url: 'https://hacktoberfestkorea.com/'

theme:
  name: material
  language: ko
  custom_dir: 'theme'
  palette:
    scheme: default
  favicon: assets/favicon.svg

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascript/ie_compatibility.js

nav:
  - Home: index.md
  - 행동 규칙 : Hacktoberfest_code_of_conduct.md
  - 왕초보자용 가이드: super_beginners_guide.md
  - 초보자용 가이드: beginners_guide.md
  - 작업환경 구성 방법: build.md
  - 자주 묻는 질문: faq.md
  - 2022년 자료 : https://2022.hacktoberfestkorea.com

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences

google_analytics:
  - UA-151967026-1
  - auto
